# Generated by Django 3.2.12 on 2024-06-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='person',
            name='id_card',
            field=models.CharField(default='00000000X', max_length=9, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
